### ISSUE TITLE
Block Cookie

### ISSUE THREAD

**Issue by matteobarale** [silktide/cookieconsent2#10]
Hi,
I've used the cookie consent plugin v1, now i'm testing the v2, but I can not find any way to block cookie.
Why?

**Comment by oliveremberton** [comment]
Cookie Consent v2 doesn't currently offer you any way to block cookies. You can still use v1 if you need that functionality.

We *might* add support for blocking in a future version, if there's enough demand for it. Our feedback on v1 was almost no-one appeared to use this feature.
