### ISSUE TITLE
Cookie Consent Stopped Working

### ISSUE THREAD

**Issue by uthans** [silktide/cookieconsent2#103]
cookie consent bar suddenly disappeared from  my site. It was working for the past 3 months without any issues. Javascript is hosted on my own website. Banner is not at all appearing on Firefox and Chrome but in Internet Explorer, it is appearing  but without STYLE(CSS).  Appreciate your guidance. 
<script>
    window.cookieconsent_options = {
        learnMore: 'more info',
        theme: 'light-bottom'
    }
</script>
<script type="text/javascript" src="js/cookieconsent.latest.min.js"></script>

**Comment by ScottSpittle** [comment]
GET http://s3.amazonaws.com/cc.silktide.com/light-bottom.css 403 Forbidden

**Comment by ScottSpittle** [comment]
The CDN was changed in the latest commit so you could just change your bower.json to 
*** 
    "cookieconsent2": "https://github.com/silktide/cookieconsent2.git#bd2894f1d339b2a717d763fbcb51c5894453a57a" ***

**Comment by Dolondro** [comment]
We unfortunately had to stop hosting the project ourselves as the hosting costs with the amount of people who were linking to it was getting untenable for a company of our size (not large).

https://silktide.com/really-important-update-to-users-of-cookie-consent-2/

Annoyingly, the CSS files linked to in the original downloaded JS link linked to our hosted copies and we obviously had no way of a) updating that or b) notifying you that something was wrong.

If you use the latest version, the CSS files now link to an external cdn service (cdnjs.com) which should have no such problems.
