### ISSUE TITLE
Missing release with fixed links ?

### ISSUE THREAD

**Issue by songoo** [silktide/cookieconsent2#109]
Hello i cant see bcbreak fix from https://github.com/silktide/cookieconsent2/commit/17dd73ceb3043bf3a35af08c55e6667cb060a8d7 in 1.0.10 release. Can it be added ?

**Comment by a780201** [comment]
[](url)

**Comment by songoo** [comment]
You can close this. I did not know i can just specify local path , that in code there is control for '.css' in name, if its missing it goes to those cursed :D external THEME_BUCKET_PATH links.
