### ISSUE TITLE
Problem as an Koken Plug-in

### ISSUE THREAD

**Issue by BlackSkorpio** [silktide/cookieconsent2#11]
Hi guys!
There has been some cries for a koken plugin version of your code, so i decided to give it a try...

Everything works fine on the "plug-in" side: and the output is what i want.
But the message is not appearing on the visitors side

On my local dev machine it does: with out any CSS applied to it.

Hoping that you could be kind to have a look maybe?
http://kokensupport.varoystrand.se/demo/

My plugin repo is here: https://github.com/BlackSkorpio/cookieconsent

Regards
Bjarne Varöystrand

**Comment by oliveremberton** [comment]
The problem appears to be how you're referencing your theme:

````
theme: '/demo/storage/plugins/cookieconsent/styles/dark-top.css'
````

`theme` can either refer to a URL for your CSS file, or the name of a built-in theme file hosted on Silktide's CDN. If the theme string contains `.css` we assume it's a URL.

In this case your value is interpreted as a URL which points here:

http://kokensupport.varoystrand.se/demo/storage/plugins/cookieconsent/styles/dark-top.css

Which is a 404 returning a HTML page, hence no CSS is loaded. If you either fix the URL or upload your CSS to that location you should be fine. If you prefer to just use our own CSS theme, simply change your `theme` to `dark-top`.
