### ISSUE TITLE
customization doesnot appear in the theme

### ISSUE THREAD

**Issue by cchristos** [silktide/cookieconsent2#113]
i have made all the necessary customization through here https://silktide.com/tools/cookie-consent/download/.
The prompt appears correctly but it has the default message and link to the cookie consent of silktide
could you be of assistance?

**Comment by Dolondro** [comment]
Sorry for the (very) delayed response, is this still an issue for you or did you work out what the problem was?

**Comment by cchristos** [comment]
I have quited the useage of the program, since I wasnot working properly
