### ISSUE TITLE
Cookie Consent 1 Goes Full Screen on Mobile Devices

### ISSUE THREAD

**Issue by kimi85** [silktide/cookieconsent2#114]
Hey there, the new geo targeting is awesome, the plugin is great but on mobiles it goes full screen. Can you resolve this? Even on your demo page it goes full screen when tested with iphone 6.

Thank you,
Csaba
![screenshot_1](https://cloud.githubusercontent.com/assets/17096356/12866233/d198c8d8-ccc7-11e5-8fcf-418cc9a8236c.jpg)

**Comment by cyskye** [comment]
Same problem for me

**Comment by cyskye** [comment]
They moved server, so new files to link are there:
https://cdnjs.com/libraries/cookieconsent2

**Comment by kimi85** [comment]
I was told that this is supposed to be like this but it makes no sense.

The good looking version has no GEO section and the unoptimized version has GEO option :/

**Comment by zevnikrok** [comment]
using the latest version from github (january 10th) and the consent doesn't fill fullscreen on mobile. This V2 version is much more simpler, with less options (just message that they are using cookies with an optional link for cookie info page and a button to accept).

But yes, it doesn't have geo option.

**Comment by kimi85** [comment]
I love that version... but why can't we have GEO targeting... I don't want to bug 90% of my visitors as an extra, I have 10% EU only.

**Comment by oliveremberton** [comment]
Oliver from Silktide here. Right now there are two versions of Cookie Consent and neither is ideal for what you describe. CC v1 supports geo targeting, but is much older (old enough to predate mobile web design) so it doesn't support phones well. CC v2 supports phones well but doesn't support geo targeting.

CC v2 was designed to be more lightweight, so non-core features got dropped, but this is one that I expect we'll add back in. We plan to work on CC v3 very soon.

Until then I'm afraid all I can suggest is either your own geo targeting wrapper that disables CC v2, or using another solution. Sorry I can't be more help.

**Comment by kimi85** [comment]
Hi Oliver, can you suggest any wrapper solution to use with CC v2?

**Comment by Dolondro** [comment]
GeoIP is indeed an enhancement but one that is already taken care of in issue #35 

This is a request for a change to http://github.com/silktide/cookieconsent
