### ISSUE TITLE
Cookieconsent2 not initialising on site

### ISSUE THREAD

**Issue by jamo81** [silktide/cookieconsent2#120]
Hi,

Cookieconsent2 was working fine but seems to have stopped initialising and showing the banner in all browsers. I've tried localising the problem using the non-minified version off github.  Here is my code:

```html
<!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
<script type="text/javascript">
    window.cookieconsent_options = {
			"message":" This website uses cookies to ensure you get the best experience on our website",
			"dismiss":"Got it!",
			"expiryDays": 365,
			"learnMore":"More info",
			"link":"https://mysite/cookies.php",
			"theme":"light-bottom"};
</script>


<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
<!--<script type="text/javascript" src="cookie-consent.js"></script>-->
<!-- End Cookie Consent plugin -->
```
I've tried using document.onload etc etc so it loads after the page has fired up.

In firebug there is a weird error:
```
uncaught exception: [Exception... "Not enough arguments" nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)" location: "JS frame :: https://mysite/scripts/js/shared/cookie-consent.js :: anonymous :: line 119" data: no]
```

This does not flag in chrome or IE so I think it is a red herring.

Any idea why it is not initialising? the cookie is not even being set.

Thanks in advance.

**Comment by Dolondro** [comment]
The Firebug error is a red herring I believe. Can you link me to the site where it isn't working?

**Comment by jamo81** [comment]
OK, thanks. https://outplaysquash.com

**Comment by Dolondro** [comment]
Works fine for me.

![image](https://cloud.githubusercontent.com/assets/1678803/13314902/873d6d5c-db9f-11e5-853e-b0348b2634fc.png)

**Comment by jamo81** [comment]
Hmm. Tried clearing my cookie history again and it worked! Still no luck in
firefox so I will look into that error.

Thanks
