### ISSUE TITLE
Incorrect theme URL in 1.9 release

### ISSUE THREAD

**Issue by roelvanduijnhoven** [silktide/cookieconsent2#121]
We noticed cookieconsent stopped working due to the theme returning a 404. After a quick scan on this repo we noticed it changed upstream and tried to update to 1.9.

However: it *still* does not work. The problem is that the `./cookieconsent.js` file in the 1.9 release still contains the incorrect link. This was fixed (https://github.com/silktide/cookieconsent2/commit/17dd73ceb3043bf3a35af08c55e6667cb060a8d7) after the release, and is thus not part of 1.9. The minified version *does* work however. So that is what I am using now.

I would suggest doing another release containing the fix.

**Comment by Dolondro** [comment]
A version 1.0.10 has been released which should fix your issue.
