### ISSUE TITLE
How to implement Cookie Consent code into website. [HELP NEEDED]

### ISSUE THREAD

**Issue by tjbruce17594** [silktide/cookieconsent2#126]
Hey everyone.

I am having trouble implementing the cookie consent code into my website. Could someone please provide me with detailed steps in installing this on my website (tjbruce17594.com)

Thanks very much!

Code I'm trying to use: 

http://pastebin.com/hcPyp1FH

Thanks for any help! :D @Dolondro

**Comment by Dolondro** [comment]
Hullo!

You want to put it inside the <head> tag in your HTML the code that reads this in your source code:

`		
		`

**Comment by tjbruce17594** [comment]
So just replace that with the Cookie Code?

**Comment by tjbruce17594** [comment]
What should the end result of the source code look like? @Dolondro

**Comment by Dolondro** [comment]
Sorry, it shouldn't replace it, it should to just underneath it. The end code will look like this:

`
	<head>
		<title>Home | tjbruce17594</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		
		<link rel="stylesheet" href="assets/css/main.css" />
		
		

<script type="text/javascript">
    window.cookieconsent_options = {"message":"I use cookies to help you have a better experience on my website.","dismiss":"Awesome!","learnMore":"More info","link":"silktide.com/tools/cookie-consent/","theme":"dark-top"};
</script>
 
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>

	</head>
`

**Comment by tjbruce17594** [comment]
Thanks very much! Working now. :) Solved.
