### ISSUE TITLE
Does this work with Bootstrap?

### ISSUE THREAD

**Issue by JemRob** [silktide/cookieconsent2#13]
Hi, I'm not a coder, I've followed the simple instructions with the wizard on Silktide to absolutely no effect. I was testing it to see if it worked and it appears that it doesn't however it may be an illusion caused by stupidity! Am I doing something wrong?

I've dropped the code into the head as instructed on www.testing123testing123.co.uk

Thank you if you can be bothered to answer with any instructions that lead to successful implementation.

Jem

**Comment by adjohu** [comment]
Hi @JemRob,

I had a look at the site you linked, but I can't see the cookie consent plugin anywhere. As far as I can see, it doesn't seem to be in the <head>. Can you make sure you've added it to your layout.

Also, yes - the plugin works with Bootstrap.

**Comment by JemRob** [comment]
I'd just taken the page down for a moment, it's back up again now, thanks

**Comment by JemRob** [comment]
Hi Adam, I’d just taken it down for a moment, it’s back up again but still not working

**Comment by adjohu** [comment]
Oops,

Looks like our wizard currently links to a local version of [`cookieconsent.js`](http://www.testing123testing123.co.uk/cookieconsent.js). I will get that fixed, but for now - you can fix it by changing:

 `<script type="text/javascript" src="cookieconsent.js"></script>` 

to

  `<script src="//s3.amazonaws.com/cc.silktide.com/cookieconsent.latest.min.js"></script>`

**Comment by JemRob** [comment]
I've swapped the layout from bow in bottom right to banner at top but still no joy.

**Comment by JemRob** [comment]
Brill thanks!

**Comment by JemRob** [comment]
Cool. it works, many thanks
