### ISSUE TITLE
SSL issue in Firefox and IE (not Chrome)

### ISSUE THREAD

**Issue by apointdironie** [silktide/cookieconsent2#132]
Ticket sent to support

URL for example site:
shop.frocrock.com

Essentially, the green padlock showing SSL is fine in Chrome, but in FF and IE, it doesn't appear until **after** consent has been given to CC.

**Comment by Dolondro** [comment]
Issue with CookieConsent 1

**Comment by MihaGasper** [comment]
So we need to update to last version?
