### ISSUE TITLE
Add CookiesOK support

### ISSUE THREAD

**Issue by smrqdt** [silktide/cookieconsent2#137]
CookiesOK is a browser plugin to get rid of cookie consent prompts. The plugin also signals websites that the user consents to cookies, explained on their [https://cookiesok.com/#developers](website). It would be great if Cookie Consent would recognize this.

**Comment by Dolondro** [comment]
It already does: https://github.com/silktide/cookieconsent2/commit/ed517ce243eae84b850e61b2fa4091a083563abd
