### ISSUE TITLE
Former version on download page

### ISSUE THREAD

**Issue by GizMecano** [silktide/cookieconsent2#138]
The current code in [the download page](https://silktide.com/tools/cookie-consent/download/) refers to former version (1.0.9):

```
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
```

While [the CDN](https://cdnjs.com/libraries/cookieconsent2/1.0.10) seems to enable [the last version](https://github.com/silktide/cookieconsent2/releases/tag/1.0.10) (1.0.10):

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.10/cookieconsent.min.js"></script>
```

**Comment by oliveremberton** [comment]
@Dolondro is this one you can fix?

**Comment by Dolondro** [comment]
Fixed

**Comment by GizMecano** [comment]
To complete this issue, could you just clarify why you prefer use `src="//cdnjs.cloudflare.com/` rather than `src="https://cdnjs.cloudflare.com/` as proposed [in the CDN](https://cdnjs.com/libraries/cookieconsent2/1.0.10)?
