### ISSUE TITLE
Customize Cookie Consent on the fly error

### ISSUE THREAD

**Issue by rsdev000** [silktide/cookieconsent2#142]
Hi. I'm trying to customize message, dismiss options on the fly without success.

This is how i'm trying

```javascript
window.cookieconsent_options = {
    "message"  : "I'm using cookies",
    "dismiss"  : "OK",
    "learnMore": "Learn more",
    "link"     : 'http://www.aboutcookies.org',
};

<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.10/cookieconsent.min.js"></script>

window.update_cookieconsent_options({
    dismiss: 'Accept it !'
});
```

The error in the console is: ``` Uncaught TypeError: window.update_cookieconsent_options is not a function ```and the button caption is not updated.

What's wrong here ?

Cheers

**Comment by nickpadgett** [comment]
@rsdev000 It's likely that the cookieconsent.min.js file is not finished loading before you try to call the function on window. To confirm this, do this:
`console.log(window.update_cookieconsent_options)`
right before you try to call the function. The output should be null.

**Comment by rsdev000** [comment]
Hi @nickpadgett . Thanks for the tip. The output in the console is "undefined" followed by the Uncaught TypeError error message.
Will try to get a workaround to detect if script is loaded and change the options after.

Cheers

**Comment by rsdev000** [comment]
Solved! Thank you very much.
