### ISSUE TITLE
Css Problem

### ISSUE THREAD

**Issue by FrankieNovy** [silktide/cookieconsent2#15]
Hi, I'm not a professional coder, I've followed the simple instructions with the wizard on Silktide.
I chose top-version light, but I have interaction problems between my website css, and cookie banner css.
Text in the banner becomes caps style not lowercase, and change the alignment of the text.
Is it possible to solve the problem and make sure that the banner have the Silktide style?

I look forward to your kind reply
Thanks

**Comment by adjohu** [comment]
Hi Frankie,

Can you try adding 

```
.cc_banner-wrapper {
	text-transform: none;
}
```

to your site's css?

That should hopefully fix it.
-- 
Adam Hutchinson
Sent with Airmail

On 11 June 2015 at 17:14:34, FrankieNovy (notifications@github.com) wrote:

Hi, I'm not a professional coder, I've followed the simple instructions with the wizard on Silktide.
I chose top-version light, but I have interaction problems between my website css, and cookie banner css.
Text in the banner becomes caps style not lowercase, and change the alignment of the text.
Is it possible to solve the problem and make sure that the banner have the Silktide style?

I look forward to your kind reply
Thanks

**Comment by adjohu** [comment]
Hi Frankie,

Can you try adding 

```
.cc_banner-wrapper {
	text-transform: none;
}
```

to your site's css?

That should hopefully fix it.
