### ISSUE TITLE
Auto-accept on scroll or click

### ISSUE THREAD

**Issue by ZaneCEO** [silktide/cookieconsent2#16]
Hi, I really like your script and I'm using it on https://turbolab.it/ .

Could you please add a two options to accept (i.e.: auto-click on the "ok" button) when the user scrolls or he/she clicks anywhere but the "more info" link? this, AFAIK, is the current law in Italy.

Thanks!

**Comment by adjohu** [comment]
Cookie Consent v2 doesn't currently offer this functionality. We're trying to keep it lightweight to keep loading times low.

We might add support for it in a future version, if there's enough demand for it.
