### ISSUE TITLE
Problem with IE 7

### ISSUE THREAD

**Issue by luca-bellenghi** [silktide/cookieconsent2#20]
Hi.
The script have problem on IE 7; someone still use it :-( 

The problem should be related to this line:
https://github.com/silktide/cookieconsent2/blob/master/cookieconsent.js#L169

**Comment by adjohu** [comment]
Cookie Consent v2 has been designed to support modern browsers (IE8+).

We do offer a [version of cookie consent which supports IE7](https://github.com/silktide/cookieconsent)
