### ISSUE TITLE
Change css

### ISSUE THREAD

**Issue by janeloxton** [silktide/cookieconsent2#24]
Hi. Please can you explain where to change css? Ive copied and edited your css and added it to Admin > SIte settings>Stylesheet editor, but it's not picking it up. 

You have said "If you wish to use your own CSS instead, specify the URL of your CSS file. e.g. styles/my_custom_theme.css. This can be a relative or absolute URL""

but you havent said where to put this code or the exact wording..
Please help

**Comment by adjohu** [comment]
Hi,

you would set it as a property inside window.cookieconsent_options

i.e.

```js
window.cookieconsent_options = {
  theme: 'styles/my_custom_theme.css'
};
```

**Comment by janeloxton** [comment]
thanks :)
