### ISSUE TITLE
gulp task "validate" breaks "gulp build" command

### ISSUE THREAD

**Issue by SteveMcArthur** [silktide/cookieconsent2#25]
The gulp task "validate" now checks that the "tag" argument has been passed. So if a user follows the instructions in the readme to build the project by running "gulp build" the build will fall over with the message "Required argument --tag not found".

This requirement looks like it was added to accommodate travis builds but breaks local builds unless you comment out/remove the offending code in gulpfile.js

**Comment by Dolondro** [comment]
#26
