### ISSUE TITLE
Just to be 100% clear - does version 2 stop cookies running if users don't click accept?

### ISSUE THREAD

**Issue by mrjcgoodwin** [silktide/cookieconsent2#27]
As per the subject line really!...

I don't think it is really clear in the docs whether this script is purely to make a nice looking but informative pop-up, or are cookies prevented from being used if the user fails to accept?

**Comment by adjohu** [comment]
It doesn't. We considered adding that functionality, but instead decided to build a solution that is as lightweight as possible, while still complying with the cookie law. 

V1 covers this use case so feel free to [check it out](https://github.com/silktide/cookieconsent2/)
