### ISSUE TITLE
CSS / SCSS / SASS

### ISSUE THREAD

**Issue by babrak** [silktide/cookieconsent2#28]
Not so much a bug, but perhaps a useful addition.
When defining custom theme, it would be useful to not be limited to CSS only (which seems to be the case), custom theme is not loaded unless it is CSS (so SCSS, does not load for me). I tried both absolute and relative URL, and neither seems to be recognised unless it is CSS.

**Comment by adjohu** [comment]
Not entirely sure what you mean - are you using a javascript scss compiler?

**Comment by FDiskas** [comment]
`theme:false` but still loading css from cdn

**Comment by babrak** [comment]
Sorry for late reply. What I mean is that this works:

**Comment by Dolondro** [comment]
SASS is a CSS preprocessor. This means that you have to run it through a compiler (such as node-sass) and it will transform it to CSS.

The browser itself has no concept of knowing how to deal with SASS, as such uploading the SCSS file to the server would serve no purpose.
