### ISSUE TITLE
Set cookieconsent_dismissed to base domain

### ISSUE THREAD

**Issue by andygambles** [silktide/cookieconsent2#32]
It would be great to be able to set the cookieconsent_dismised to .domain.com rather than www.domain.com then it would cover the site sub-domains such as blog.domain.com.

**Comment by adjohu** [comment]
Hey,

We just released a new version with this functionality! #31

You just need to set the `path` option.

**Comment by andygambles** [comment]
Is this deployed to aws? 

To use then in the options I should specify "path":".domain.com"
