### ISSUE TITLE
There is a syntax error on line 4

### ISSUE THREAD

**Issue by simply-does-it** [silktide/cookieconsent2#34]
Created EU compliance code using your webpage
(https://silktide.com/tools/cookie-consent/download/). 
Got this error, here's line 4:

window.cookieconsent_options = {"message":"This website sometimes places cookies to enable you to fully experience our website","dismiss":"Fine by me!","learnMore":"More info","link":"http://www.xyz.com/choose/cookies.php","theme":"dark-top"};
I'm rotten at javascript.
 
Please would you tell me what is the error and how to fix it.
My thanks in advance.

**Comment by adjohu** [comment]
Looks alright to me, could you link me to the site where the error is occurring/take a screenshot of the full error? What browser are you using?

**Comment by simply-does-it** [comment]
Thank you for replying. Your answer helped me to look at this situation further, and I find, in fact, it is a mix of two problems.

The first is I used Dreamweaver to make your code into a .js file that could be included in the head section of the pages. Dwr is stupidly picky and gives out errant messages such as this syntax error message.

And this leads me to the second problem, which was generated by me, but for which I would like your input/advice. 
Our web site has over 2,000 pages and I'd prefer to put <script language="javascript" type="text/javascript" src="/choose/cookies.js"></script>, rather than several lines of code into the <head> section. Of course, this cannot work because the code in cookies.js is the silktide.com code that includes "cookieconsent.latest.min.js"!

Is my cunning plan just plain unworkable, or can you advise how it can be made to work?

Thanking you again for your help, and your patience,

**Comment by adjohu** [comment]
I'm not exactly sure what you mean.

Here's our [full installation guide](https://silktide.com/tools/cookie-consent/docs/installation/)

The script should be included within your html.
