### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Silver-Fox** [silktide/cookieconsent2#37]
Hi,

Can anyone help me customise the cookie disclosure notice which is displayed on my website using cookieconsent2? 

I understand that I need to create my own CSS stylesheet file and then link to it in the code for the cookie plugin, but I don't understand how to specify the height of the cookie disclosure pop up and font size etc within the CSS stylesheet. In other words, how exactly to I specify the disclosure notice height and font size in the CSS stylesheet?

Many thanks.

**Comment by jbarradas** [comment]
Hey there. I can help you on that. But I realize that is already styled. Do you have any ideas in mind?

**Comment by adjohu** [comment]
[Here's the css](https://gist.github.com/adjohu/4ddb1b74d20f539d5bd7) for our dark top of the page theme. You should be able to tweak it to your own needs.

**Comment by Silver-Fox** [comment]
Thanks
