### ISSUE TITLE
Error message in IE9: property or method querySelectorAll is not supported by this object

### ISSUE THREAD

**Issue by rpijlman** [silktide/cookieconsent2#38]
In IE 9 (9.0.8112.16421 on Windows 7) http://s3.amazonaws.com/cc.silktide.com/cookieconsent.latest.min.js fails with this error message in the Javascript console:

SCRIPT438: De eigenschap of methode querySelectorAll wordt niet ondersteund door dit object 
cookieconsent.latest.min.js, regel 1 teken 1815

That's in Dutch.Translated back to English it says: The property or method querySelectorAll is not supported by this object.

**Comment by gavincompton** [comment]
I get this too, but only in compatibility mode. IE version 9.0.8112.16421, Windows 7

**Comment by adjohu** [comment]
IE7 compat mode?

**Comment by rpijlman** [comment]
Ah yes, IE was in compatability mode. No idea why. Thanks. I guess this isn't a bug then?
