### ISSUE TITLE
confirm link points to "#null"

### ISSUE THREAD

**Issue by simahawk** [silktide/cookieconsent2#4]
Is there any reason for this? I see that in previous version you get just "#" which is fine :)

**Comment by adjohu** [comment]
If the confirm link pointed to `#`, the user would be sent to the top of the page when they clicked it. `#null` allows us to avoid this as (most) pages don't have an `#null` anchor on them.

**Comment by adjohu** [comment]
#8 should have stopped `#null` from appearing in the url bar

**Comment by simahawk** [comment]
great, tnx :)

**Comment by chhantyal** [comment]
Can we make a release with this fix please? #null on url looks ugly indeed.

**Comment by adjohu** [comment]
https://github.com/silktide/cookieconsent2/tree/1.0.3

**Comment by chhantyal** [comment]
Wow - that was quick. Thank you :)
