### ISSUE TITLE
Add target="_blank" and rel="nofollow" as options

### ISSUE THREAD

**Issue by Wanabo** [silktide/cookieconsent2#40]
Needed target="_blank" and rel="nofollow"  as attributes to the read more link.
I modified the cookieconsent.js accordingly. I see recent also target="_blank" is added here on github.

It would be great if these attributes could be options and you activate them like so:
		window.cookieconsent_options = {"message":"Example message.","dismiss":"Got it!","learnMore":"More info","link":"http://www.example.com/privacy","target":"_blank","rel":"nofollow","theme":"dark-top"};

Regards Wanabo.

**Comment by vojtasvoboda** [comment]
Target blank for more info +1

**Comment by oliveremberton** [comment]
We haven't added this feature yet (there's a separate request pending), but in the meantime you can do this yourself by customising the HTML, see: https://github.com/silktide/cookieconsent2/issues/75

**Comment by vojtasvoboda** [comment]
I think it's already added, see https://github.com/silktide/cookieconsent2/blob/master/cookieconsent.js#L236

I tested it and works.

**Comment by oliveremberton** [comment]
You're right. I've updated the docs to say as much - thanks.

**Comment by vojtasvoboda** [comment]
Thanks :+1:
