### ISSUE TITLE
Generate built/minified js/css for easier dissemination to CDNs like cdnjs and jsDelivr

### ISSUE THREAD

**Issue by ping** [silktide/cookieconsent2#44]
I appreciate that silktide provides a cdn solution via AWS but I think this project will make a great addition to opensource CDNs like cdnjs.com https://github.com/cdnjs/cdnjs and jsdelivr.com https://github.com/jsdelivr/jsdelivr.

To facilitate that, it will require built/minified versions of the js + css files to be included in the project files (perhaps under a dist/ folder), so that those opensource CDNs can auto-pull and update their repos whenever a new release is available.

**Comment by Dolondro** [comment]
Done! (And is now available on CDNJS)
