### ISSUE TITLE
Unsure how to customize the css

### ISSUE THREAD

**Issue by Geert81** [silktide/cookieconsent2#45]
Hi, 

I'm unsure how to customize everything.
I'm trying to run everything locally (on my server) so I can then make changes in _bottom.scss and _light.scss (I want to use the bottom light theme).

But I'm unsure what I need to change the 
  // The path to built in themes (s3 bucket)
  var THEME_BUCKET_PATH = '/cookieconsent/styles/';

to.

Everything is in the /cookieconsent/

folder of my site and the structure is the same as the zip I've downloaded. So can you please help and explain what I should use as the bucket_path? Since when I leave it like this it doesn't work. When I return it to //s3.amazonaws.com/cc.silktide.com/ it does, but then I can't change anything.

Thanks!

**Comment by Geert81** [comment]
and could I please get the full .css file for the light bottom that I should use? Thank you so much!

**Comment by adjohu** [comment]
Hey, you don't need to change the bucket path at all.

We check the `theme` option and load the styles based on that.

If it's set to `somethingendingwith.css` then it will load the specified css file. If it doesn't end with `.css` i.e. `theme: 'dark-top'`, it will load our default theme.
