### ISSUE TITLE
Once set, how to avoid cookie consent alert on subdomains

### ISSUE THREAD

**Issue by wwwgo2be** [silktide/cookieconsent2#48]
I have implemented this easy script and it just works great.

I only notice that that cookie consent message is showing each time on every subdomain of my website (www.mydomain.com, sub1.mydomain.com, sub2.mydomain.com) instead of once for all mydomain.com sites.
Example: www.go2.be, apple.go2.be, basket.go2.be)
Could this become a feature to add or do you have some advice how to customize like that ?

**Comment by wwwgo2be** [comment]
The solution to share cookie between subdomain and domain seems to be to set the domain property of the cookie (by preference with a period before the domain name), but I have no idea how to modify the script accordingly. Can someone advice?

**Comment by adjohu** [comment]
You can change the `domain` option. [See the docs](https://silktide.com/tools/cookie-consent/docs/installation/)
