### ISSUE TITLE
Setting expiryDays (bug?)

### ISSUE THREAD

**Issue by Wanabo** [silktide/cookieconsent2#49]
When checking the functionality of cookieconsent I find myself confused.
According to the docs; "expiryDays (integer) Default: 365 The number of days Cookie Consent should store the user’s consent information for. "

But when checking the cookie that has been set it expires "At end of session", in stead of 365 days in the future. So I explicitly set expiryDays in the options. window.cookieconsent_options = { expiryDays: "365" }; But it still is "At end of session".

Regards.

**Comment by Wanabo** [comment]
Ok it seems my FireFox AddOn CookieController messed things up. I had my domains white listed but for some reason the whitelist was gone.

After white listing my domains the cookieconsent_dismissed cookie got an expiry date far into the future, 2052!!
After removing  expiryDays: "365" from options I got exactly 1 year (default behavior) into the future for an expiry time. So that's good. Remains the question why  expiryDays: "365" in options gives an expiry date in 2052.

Regards.

**Comment by mdenti** [comment]
@Wanabo : that's probably because expiryDays should be set to a number, not a string.
So expiryDays: 365 should work instead of expiryDays: "365".

**Comment by Wanabo** [comment]
Thanks, that would explain it.
