### ISSUE TITLE
Syntax for - container (string: CSS selector)

### ISSUE THREAD

**Issue by HmmmUK** [silktide/cookieconsent2#53]
Hi, sorry to be so dim! 

I'm trying to use:
container (string: CSS selector) 
The element you want the Cookie Consent notification to be appended to.

This option should change the position of my cookie banner in a modification I'm attempting.
As per the docs the default is body. Using "container":"body" in the JS also works fine. Changing this to "container":"cookies" and adding a < cookies >< /cookies > tag in the html where I want the banner displayed also works fine - BUT not in IE8. It looks like IE8 requires a supported tag.

Cheating by using a < h6 >< /h6 > seems to work in all browsers but I would like to use the "string: CSS selector" syntax rather than my dodgy hack.

Can someone give me an example of how the option 'container (string: CSS selector)' should look?
I've tried all sorts of things but can't grasp it! 
Thanks.

**Comment by HmmmUK** [comment]
Having Google link directly to you can/should be a great thing for a company!!!
BUT if you've abandoned this project and your users, it can backfire...

#JustThinkingOutloud

**Comment by adjohu** [comment]
Hey, you should be able to use a standard css selector i.e. `<div class="thisClassname">` would map to the css selector `div.thisClassname`. There's nothing wrong with using a h6, but using a class allows you to be more specific.
