### ISSUE TITLE
IE8: "Object doesn't support this property or method"   V1.0.6

### ISSUE THREAD

**Issue by HmmmUK** [silktide/cookieconsent2#54]
Using V1.0.6 
I'm still seeing some problems with IE8. 
The same code works fine with FF/Chrome but IE8 gives me the following error (using unminified script):

Message: Object doesn't support this property or method
Line: 183
Char: 7
Code: 0

Line 183:
var els = dom.parentNode.querySelectorAll('[' + attribute + ']');

EDIT:
It looks like this is down to the DOCTYPE.
I've got some ancient pages! Anyway of having IE8 work with QuirksMode or:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

**Comment by mxdpeep** [comment]
IE8 is deprecated browser

**Comment by HmmmUK** [comment]
Yes, but many cookie scripts can work fine with IE8 and QuirksMode - so depreciated or not, will Google be happy for AdSense publishers to work like this?

**Comment by mxdpeep** [comment]
can you post an example site?

**Comment by HmmmUK** [comment]
Here you go: http://www.hmmm.ip3.co.uk/bt-master-socket-nte5.shtml 
Working in FF & Chrome but IE8 gives this error: 

Message: Object doesn't support this property or method
Line: 1
Char: 1815
Code: 0
URI: www.hmmm.ip3.co.uk /cookieconsent.js

That seems to be pointing around here in the script:
{var i=e.parentNode.querySelectorAll("["+t+"]");

The newer pages on my site work fine with IE8 it's just the ancient ones running in QuirksMode that have the issue.

NB. I'm using a (GitHub supplied) hack to hide the banner after it's been seen on one page without visitors having to click - so using IE's InPrivate browsing works well for trouble shooting else the banner will automatically hide.

**Comment by Dolondro** [comment]
If you're running in QuirksMode then IE runs like it's IE7 which isn't something we support.
