### ISSUE TITLE
Add option to cycle themes

### ISSUE THREAD

**Issue by dreckbaer** [silktide/cookieconsent2#55]
Hi all!

First of all thanks for the great work you've done so far! 
Just a small suggestion to add some usability: It would be great if you could add an option that allows us to cycle the default themes, either randomly or by choice.

Thanks and keep up the good work!

**Comment by drball** [comment]
I can't think of any reason why you'd want to do this though, a user will likely only see the banner once, and if they decide not to click and see it a second time, wouldn't it be confusing if it looked different the 2nd time?
