### ISSUE TITLE
Help with code for showing to EU only

### ISSUE THREAD

**Issue by michaelvi** [silktide/cookieconsent2#64]
Hello. I found on sitebeam website that you can add code so that your cookie policy banner so that it only shows to EU visitors : cc.initialise({
	cookies: {},
	settings: {
		onlyshowwithineu: true,
		ipinfodbkey: '[YOUR API KEY]'
	}
});

I have an API Key but I am very new to web building (I have a simply built site I modified from a template) and don't know java script. I want to use cookie consent version 2.0 that is on the Silktide website but there is no place in the wizard that talks about showing only to EU visitors. 

My code from the Silktide wizard is:

<script type="text/javascript">
    window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"Read policy","link":"http://www.behappyzone.com/privacy.html","theme":"light-top"};
</script>

<script type="text/javascript" src="//s3.amazonaws.com/cc.silktide.com/cookieconsent.latest.min.js"></script>

My question is can I put the code I got from Sitebeam somewhere in the code I got from Silktide wizard so that it only appears to EU visitors. If so where? Sitebeam has a wizard but it has all sorts of questions about cookies which I don't understand and also does not add a link to my privacy policy. Sitebeam and Silktide are either the same company or related companies I'm not sure which.

If anyone can help me with this I would appreciate it. Thank you.

**Comment by Dolondro** [comment]
Hi there! Sorry for the long wait time for a response!

We (slightly confusingly) have 2 different cookie consent solutions, cookieconsent and cookieconsent2.

cookieconsent2 (where you are at the moment) doesn't currently support limiting the banner to only those inside the EU.

As such, if you want to do limiting based on IP, you'd need to use the v1 client through the [appropriate wizard](http://sitebeam.net/cookieconsent-v1/code/)

If you have any specific questions regarding using that I can try and help you.

Doug
