### ISSUE TITLE
Google Page Speed Insights Suggestions

### ISSUE THREAD

**Issue by db012** [silktide/cookieconsent2#68]
Hello,
thank you for your awesome work.

These are suggestions from Google Page Speed tool:

Leverage browser caching
Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
Leverage browser caching for the following cacheable resources:

    http://s3.amazonaws.com/…silktide.com/cookieconsent.latest.min.js (expiration not specified)
    http://s3.amazonaws.com/cc.silktide.com/dark-bottom.css (expiration not specified)
    https://s3-eu-west-1.amazonaws.com/…ent.silktide.com/cookie-consent-logo.png (expiration not specified)

Enable compression
Compressing resources with gzip or deflate can reduce the number of bytes sent over the network.
Enable compression for the following resources to reduce their transfer size by 4.7KiB (63% reduction).

    Compressing http://s3.amazonaws.com/…silktide.com/cookieconsent.latest.min.js could save 2.5KiB (57% reduction).
    Compressing http://s3.amazonaws.com/cc.silktide.com/dark-bottom.css could save 2.2KiB (71% reduction).

Do you think you could fix it?
Thank you so much

**Comment by grobmeier** [comment]
+1, was about to report myself. I would like to keep the ability to load the latest version, but...

Cache time should be minimum one day - i think that would be acceptable even for the cookie use case. Reference: https://developers.google.com/speed/docs/insights/LeverageBrowserCaching?hl=en

You could upload js and css files like that (assuming you use AWS cli):

```
aws s3 sync ${BUILD_FOLDER} ${BUCKET} --exclude "*" --include "css/*" --cache-control "max-age=604801" --content-encoding "gzip" --delete --profile YOUR_PROFILE --region REGION --acl public-read
```

Please note exclude/include directives could be easier in your case. The profile is the name of your AWS profile as stored in ~/.aws/config, looking like:

```
[profile webdeploy]
aws_access_key_id = XXX
aws_secret_access_key = XXX
```

(or similar)

**Comment by DenisMir** [comment]
+1

**Comment by zdrav4o** [comment]
+1

**Comment by RichardHancock** [comment]
This seems to be fixed now due to the CDN move.

**Comment by oliveremberton** [comment]
Yes we should have addressed all of these issues since we moved Cookie Consent from AWS to CloudFlare. 

Be sure to change your URL:

`src="//s3.amazonaws.com/cc.silktide.com/cookieconsent.latest.min.js"`

to

`src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"`

and that should fix it.
