### ISSUE TITLE
multilingual support for text/link options

### ISSUE THREAD

**Issue by simahawk** [silktide/cookieconsent2#7]
It would be really helpful to have the possibility to pass text values as:
```
message: {'en': 'english text', 'it': 'italian text',}
dismiss: {'en': 'english text', 'it': 'italian text',}
learnMore: {'en': 'english text', 'it': 'italian text',}
link: {'en': 'link/to/english/policy', 'it': 'link/to/italian/policy',}
```
then you can simply provide a "language option" to set on the fly based on you portal language mgmt.
This could be a data attribute or a JS var to lookup, or just an option to pass explicitly, like
```
window.cookieconsent_options.language = 'en'
```

**Comment by adjohu** [comment]
Pull request #8 adds the ability to change cookie consent options on the fly using 
`window.update_cookieconsent_options({newOptions})`.

You could use this in your language switcher to change the strings.
