### ISSUE TITLE
Only showing cookie to those within the EU

### ISSUE THREAD

**Issue by uncov** [silktide/cookieconsent2#70]
Hi,

I noticed on the first version (sitebeam.net/cookieconsent-v1/code) there was an option to exclude the cookie bar showing to those outside the EU by integrating with the IPInfoDB.  Is that not an option with the latest version?

Thanks,

Paul

**Comment by adjohu** [comment]
Hi Paul,

We've tried to make this version much more lightweight. V2 currently doesn't support IP based triggering, but feel free to use the old version if that better suits your needs.
