### ISSUE TITLE
How to show multiple promts?

### ISSUE THREAD

**Issue by salili** [silktide/cookieconsent2#71]
Hello,

how can I show two or more promts, each with different options (headline, link etc) at the same time? Is it possible without altering the script (cookieconsent.latest.min.js)?

Thanks!

**Comment by Dolondro** [comment]
Hi!

This isn't something that we support and it isn't a use case we're planning on supporting, so you'll end up having to craft your own solution unfortunately!

Regards

**Comment by salili** [comment]
Thanks Dolondro!
