### ISSUE TITLE
Text size issue in IE10

### ISSUE THREAD

**Issue by europadev** [silktide/cookieconsent2#72]
Hi, 

Apologies if this is a stupid question!

I've just installed the script and it works fine in Chrome and FF but for some reason in IE10 the text size within the popup is very small.

Any idea on what it may be?

Thanks

**Comment by drball** [comment]
Hi I've just tested this on our implementation of the banner on silktide.com in IE 10 but don't seem to have a problem. Could you point me to a website where this is an issue? I wonder if there's possibly some IE-specific styles that could be overriding the styles?

**Comment by oliveremberton** [comment]
Closing as no response.
