### ISSUE TITLE
Privacy Policy link /banner does not disapear using Internet Explorer

### ISSUE THREAD

**Issue by chrismagenta** [silktide/cookieconsent2#74]
Hi, everything working fine now except in Internet Explorer the "privacy banner/link" keeps appearing after the cookie accept button has been used. The code is set to off. See below.
 
see http://accountants.usa121.com in explorer for problem.
 
What can I do to fix this problem.????
 
Chris

// <![CDATA[
cc.initialise({
	cookies: {
		advertising: {}
	},
	settings: {
		hideprivacysettingstab: 'true'
ertc............

**Comment by Dolondro** [comment]
Your website appears to be using [CookieConsent v1](http://github.com/silktide/cookieconsent) and thus this is not the right place for this question.
