### ISSUE TITLE
set link to target: _blank

### ISSUE THREAD

**Issue by geocluj** [silktide/cookieconsent2#75]
how can I set the "more info" link to open in a new tab ?
thanks

**Comment by aish1550** [comment]
This is something I was also trying to get merged to master please see my same issue and suggestion. 
I have created a pull request for this but not much movement just yet on having it merged to master

Issue
https://github.com/silktide/cookieconsent2/issues/52

My pull request
https://github.com/silktide/cookieconsent2/pull/73

Temporary solution for now.
What you can do is pull your JS from my repo for now until Silktide comeback with a solution for this. 
just add your script src to here
http://cdn.rawgit.com/aish1550/cookieconsent2/master/cookieconsent.js

and then your config object something like this

window.cookieconsent_options = {
          message: 'Cookies help us deliver our services. By using our site, you agree to our use of cookies. ',
          learnMore: 'Learn more',
          dismiss: 'Ok',
          link: 'YOUR-LINK-HERE',
          target: '_blank',
          theme: 'light-top'
       };

**Comment by mdenti** [comment]
if this is not being worked on or the fix is not being considered, you have the option to use the markup option to personalize the html, like so:

```javascript
window.cookieconsent_options = {
      message: 'This website uses cookies to ensure you get the best experience on our website. ',
      dismiss: 'Got it!',
      learnMore: 'More info',
      link: 'your_link',
      theme: 'light-floating',
      markup: [
        '<div class="cc_banner-wrapper {{containerClasses}}">',
        '<div class="cc_banner cc_container cc_container--open">',
        '<a href="#null" data-cc-event="click:dismiss" target="_blank" class="cc_btn cc_btn_accept_all">{{options.dismiss}}</a>',

        '<p class="cc_message">{{options.message}} <a target="_blank" data-cc-if="options.link" class="cc_more_info" href="{{options.link || "#null"}}">{{options.learnMore}}</a></p>',

        '<a class="cc_logo" target="_blank" href="http://silktide.com/cookieconsent">Cookie Consent plugin for the EU cookie law</a>',
        '</div>',
        '</div>'
      ]
};
```

**Comment by aish1550** [comment]
Absolutely. If this works and has no compatibility issues then yep definitely! As far as movement on the fix k proposed, I believe it has been reviewed and merged or if not yet, I believe it will be. Pretty sure I got confirmation of that but will come back to you once I've double checked that

**Comment by Dolondro** [comment]
Thanks! Accepted the Pull Request, will push out a new version in the next few days

**Comment by achimmer** [comment]
Is there way to not set target="_blank" but rather have the value "_self"?

**Comment by aish1550** [comment]
I believe there is, I haven't looked at this plugin for a bit. Pretty sure you should be able to go into the default settings of the plugin and change those although it would be a unique solution. Let me give a more definitive answer tomorrow once I've looked at it again.

**Comment by aish1550** [comment]
@achimmer Did you figure it out? and what's your timeline? If it's tight, probably worth getting in Touch with Doug. He's the guru behind the plugin.

**Comment by ratnayake** [comment]
```
elements: {
                    header: '<span class="cc-header">{{header}}</span>&nbsp;',
                    message: '<span id="cookieconsent:desc" class="cc-message">{{message}}</span>',
                    messagelink: '<span id="cookieconsent:desc" class="cc-message">{{message}} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_self">{{link}}</a></span>',
                    dismiss: '<a aria-label="dismiss cookie message" tabindex="0" class="cc-btn cc-dismiss">{{dismiss}}</a>',
                    allow: '<a aria-label="allow cookies" tabindex="0" class="cc-btn cc-allow">{{allow}}</a>',
                    deny: '<a aria-label="deny cookies" tabindex="0" class="cc-btn cc-deny">{{deny}}</a>',
                    link: '<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_blank">{{link}}</a>',
                    close: '<span aria-label="dismiss cookie message" tabindex="0" class="cc-close">{{close}}</span>',
                },
```

this will do the trick
