### ISSUE TITLE
Smarty issue

### ISSUE THREAD

**Issue by 814DA** [silktide/cookieconsent2#77]
Wanting to use this on a classified ads site that uses the Smarty template system. I'm using the wizard to generate the code.
Problem is that I get a Smarty error: 'Fatal error: Smarty error: [in header.tpl line 31]: syntax error: unrecognized tag: "message":'
Wrapping the javascript in {literal}{/literal} tags stops the error but the cookie consent dropdown doesn't show up on the site.

Thanks for any suggestions!

**Comment by SevenOaksKR** [comment]
We've got the same problem!

**Comment by oliveremberton** [comment]
I'm not familiar with Smarty, but what you describe sounds like you need to escape our code before you can use it. Otherwise our Javascript is being seen as part of your Smarty template.

Smarty's docs on this are here: http://www.smarty.net/docsv2/en/language.escaping.tpl
