### ISSUE TITLE
Cookie consent does not appear on pages from 2nd level on concerning URL structure

### ISSUE THREAD

**Issue by Sebastian-Pohl** [silktide/cookieconsent2#78]
Hi everybody, shortly: on http://entsafter-preisvergleich.de/ or http://entsafter-preisvergleich.de/entsafter-preisvergleich.php it is showing up, but not on http://entsafter-preisvergleich.de/rezepte/uebersicht.php e. g. Further searching for myself, but maybe it is simple to resolve. My only approach currently is to check the delivered JavaScript given by http://s3.amazonaws.com/cc.silktide.com/cookieconsent.latest.min.js. Thanks in advance, Sebastian

**Comment by croesike** [comment]
The Javascript returns an error because you're pointing to the wrong CSS File: http://entsafter-preisvergleich.de/rezepte/css/cookie-consent_angepasst.css 

It should work after fixing that.

**Comment by Sebastian-Pohl** [comment]
Thanks croesike,

fixed it. Logical.

Simply added a '/' before the path in the value for 'theme' and therefore made the path less relative:

<script>
    	window.cookieconsent_options = {
    		message: 'Cookies helfen uns bei der Bereitstellung unserer Dienste. Durch die Nutzung unserer Dienste erkl&#228;st du dich damit einverstanden, dass wir Cookies setzen.',
    		dismiss: 'Okay',
    		learnMore: 'Mehr erfahren',
    		link: 'http://entsafter-preisvergleich.de/datenschutz.php#cookies',
    		theme: '/css/cookie-consent_angepasst.css'
    	};
</script>

.
