### ISSUE TITLE
Force Show

### ISSUE THREAD

**Issue by francescop** [silktide/cookieconsent2#79]
Hello, is possible to force showing the bar even after the user has accepted the cookies? It will surely be useful for testing purposes.

**Comment by drball** [comment]
Hi, yes it's possible to get the bar to show again by deleting a cookie. If you use Google's developer tools you can go to resources, then Cookies > localhost, you'll see a cookie called "cookieconsent_dismissed". Delete this and it'll show the banner again.

**Comment by francescop** [comment]
hello, yes i know it can be done by deleting a cookie. i am wondering if there's an option (kinda of forceShow: true) that shows it without deleting any cookie, like Jquery-Cookiebar does :)

**Comment by drball** [comment]
I can't think why anyone would need this feature though? The user would want to press "accept" and never get interrupted by this banner again.

**Comment by francescop** [comment]
From the developer perspective, I think that that feature would be useful. For example, if you are styling the bar and you might want to edit it after some times, you do not have to delete the cookie manually. If you think that could be useful I could develop that feature.

**Comment by colinurbs** [comment]
I came here looking for this exact feature, it's a pain testing out my custom css.
