### ISSUE TITLE
Alternative license

### ISSUE THREAD

**Issue by mwaclawek** [silktide/cookieconsent2#82]
Awesome library!

Maybe you should think about switching to another license:

The GPL license is [not](http://stackoverflow.com/questions/1239470/restrictions-of-gpl-on-javascript-libraries) [really](http://programmers.stackexchange.com/questions/62869/how-is-client-side-javascript-covered-by-the-gpl) [adequate](https://www.quora.com/How-safe-is-it-to-use-a-GNU-GPL-2-library-for-a-website) for client-side JavaScript code, one may argue.

**Comment by drball** [comment]
Thanks that is a great suggestion!

**Comment by Dolondro** [comment]
Changed the licence to be MIT. Feel free to do as you want with it!
