### ISSUE TITLE
not showing

### ISSUE THREAD

**Issue by Blazenko80** [silktide/cookieconsent2#84]
Hi,
I've installed the cookie-code but it is not showing.

http://www.augenop.org/

Hopefully you can help me to find a solution.

Thank you,

Blazenko

**Comment by dreckbaer** [comment]
I can see the cookie disclaimer on your website. 
![image](https://cloud.githubusercontent.com/assets/13910970/10136134/18beaea8-65f3-11e5-9d95-09552c6eff2f.png)

**Comment by Blazenko80** [comment]
Thank you! Yes, I fixed it, already.
Best regards,
Blazenko

**Comment by uthans** [comment]
Will this work on Local Machine.  CookieConsent is not working when I tested on local C:// drive.  I put the following code just before closing </head> section and tested on local computer. But not working at all. I want to make sure that the code is working before uploading into the server.
<script type="text/javascript">
    window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":"http://www.mywebsitie.com/cookie-policy","theme":"dark-bottom"};
</script>

<script type="text/javascript" src="//s3.amazonaws.com/cc.silktide.com/cookieconsent.latest.min.js"></script>
Thanks

Uthan
