### ISSUE TITLE
cc_banner-wrapper height on the basis of device.

### ISSUE THREAD

**Issue by tanujainnextag** [silktide/cookieconsent2#85]
we are using the script for desktop as well as mobile sites.
height of cc_banner-wrapper(relative block) is 66px . so for devices like ipad on which the inner content in 'cc_banner cc_container cc_container--open container'(fixed block) comes in multiple lines it's height increases and it hides the content below it. is there any portable solution for all mobile devices(so that height of cc_banner-wrapper is set to height of cc_banner)? do we have nay callback function?

**Comment by drball** [comment]
Hi, I'm not sure of a good solution though, if the height of the banner didn't increase the text would get clipped!

**Comment by tanujainnextag** [comment]
I don't want text to be clipped so i can't keep my height fixed. i want its height to change dynamically and set accordingly so that content below it also doesn't hide.

**Comment by drball** [comment]
If you don't want content to be hidden behind the banner, how about using the version that pushes the content down, instead of covering it. It's the 5th option from the left on this page https://silktide.com/tools/cookie-consent/download/

**Comment by cyskye** [comment]
Tried to change visibility options but in mobile devices notification covers all the screen... can you help?
