### ISSUE TITLE
Cookie Consent not working when tested on C:/ (local Machine)

### ISSUE THREAD

**Issue by uthans** [silktide/cookieconsent2#86]
I just followed your instructions to install the code you have provided on your silktide website. When I tested on local machine, it is not working at all.  I just want to test it before putting into the server. 

Thanks 

Uthan

**Comment by drball** [comment]
Hi, you haven't given us enough info to accurately diagnose this problem you're having, however it sounds like you're having browser security issues (eg the script is being prevented from running because you're running it on c://), have you tried running it on localhost?

**Comment by uthans** [comment]
Dear David Ball,

Thanks for the reply. I do not have any browser security issues as I am
able to view other scripts without any problem.  I have no issues when I
add your other scripts given below.
<link rel="stylesheet" type="text/css" href="
http://assets.cookieconsent.silktide.com/current/style.min.css"/>
<script type="text/javascript" src="
http://assets.cookieconsent.silktide.com/current/plugin.min.js"></script>

This script doesnt suit to my websiite as it is only showing  a Privacy
Button on the bottom of the website and the users have to click on it and
choose the options. I was looking for a single bar notification and I love
your cookieconsent2 design. Unfortunately, the script is not working for me
when I test it on C:// drive. I didn't try to running it on localhost. I
thought when your other script is working perfectly, cookieconsent2 also
will work.    Do I need CSS or any html code to be used between <body>
</body> in order to work this script??  Appreciate your guidance. The Code
I used is given below.

<script type="text/javascript">
    window.cookieconsent_options = {"message":"This website uses cookies to
ensure you get the best experience on our website","dismiss":"Got
it!","learnMore":"More info","link":"http://www.mywebsite.com/cookie-policy
","theme":"dark-top"};
</script>

<script type="text/javascript" src="//
s3.amazonaws.com/cc.silktide.com/cookieconsent.latest.min.js"></script>

Cheers!

Uthan

**Comment by uthans** [comment]
This is in continuation of my yesterdays email. I got ride of the issue
today. it worked after I added cookieconsent.latest.min.js  and
light-bottom.css + the html code in the body section. But I experience a
new issue which is the banner is not closing when I click on "Got it" . Is
this because I tested on C:// ? Do I need to do any changes on JS?  This is
the html code I used.

<div class="cc_banner cc_container cc_container--open">
<a class="cc_btn cc_btn_accept_all" data-cc-event="click:dismiss"
href="#null">Got it!</a>
<p class="cc_message">This website uses cookies to ensure you get the best
experience on our website </p>
<a class="cc_logo" href="http://silktide.com/cookieconsent"
target="_blank">Cookie Consent plugin for the EU cookie law</a>

Thank You very much.

Uthan

**Comment by drball** [comment]
Use the code from this page instead of adding the html directly to your page: https://silktide.com/tools/cookie-consent/download/

**Comment by uthans** [comment]
Hi DrBall
I tried using the code on the above link. But the result is same

**Comment by Dolondro** [comment]
Hi Uthans! What browser are you trying this in?

**Comment by uthans** [comment]
I tried on both Firefox and Chrome.

Thanks

Uthan

**Comment by uthans** [comment]
Cookie banner is not closing even after hosting on local server. I downloaded the code from silktide but not working for me without css. When I link css, the script is working but not closing when I click on "Got it".
thanks.
Uthan

**Comment by oliveremberton** [comment]
Sorry I don't think we're able to help here, we can't reproduce this problem.

One thing you could try that might help: try this in Chrome, and open the Developer Tools > Console before clicking on the "Got it" button. If it doesn't work, we'd expect to see an error message displayed there. If you're able to show us that error we might be able to figure out the problem.
