### ISSUE TITLE
Display only on 1st page load

### ISSUE THREAD

**Issue by bshilpaa** [silktide/cookieconsent2#94]
Hello,

I am not a developer and we have added the javascript directly into our CMS as below

<script type="text/javascript">
    window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":null,"theme":"dark-bottom"};
</script>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js">
</script>

Can you let me know where to add the code "document.cookie="cookieconsent_dismissed=yes; path=/; domain=.yourdomain.com; so that I can avoid showing the cookie consent on every page?

Also, the css is not loading properly as the cookie consent text is not visible and is appearing in black.
Can you please help me?
![cookieconsent text appearing in black](https://cloud.githubusercontent.com/assets/15670290/10967506/19789182-83b3-11e5-959c-1f2ecc6a7554.jpg)

**Comment by oliveremberton** [comment]
You will have a line of code like this (note, yours will be different depending on the options you chose):

```javascript
window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":null,"theme":"dark-top"};
```

You need to add your new options in the same format, before that closing `}` curly brace:

```javascript
window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":null,"theme":"dark-top","path":"/", "domain":".yourdomain.com"};
```

That will take care of the domain and path. You also mentioned `cookieconsent_dismissed` but I don't know what that is, so I can't help you there.

To set the CSS, just set the value of `"theme"` to the web address of your CSS file.
