### ISSUE TITLE
Set Cache-Control header on S3 to save money

### ISSUE THREAD

**Issue by peda** [silktide/cookieconsent2#95]
Hello, I've had a similar issue with one of my services in the past and I did save a lot of money by setting a cache-control header in S3 - this can easily be done in the metadata (as seen on the attached screenshot)

![bildschirmfoto von 2015-11-09 18 55 56](https://cloud.githubusercontent.com/assets/559490/11041716/b0ce7dae-8713-11e5-9281-0e2001ecbd22.png)

You probably don't change the script that frequently and even a few hours of caching do save a hell lot of money because the script is not requested that often. 

Not sure how much (or if anything at all) this would save in your case but you could at least give it a try - if it significantly reduces cost you might even be able to extend the switch over period (I'm sure many people will not read your email at the first glance, because mail services like gmails do auto filter it).

**Comment by peda** [comment]
In addition there is the possibility to switch the S3 bucket to static website hosting mode - in this mode S3 does allow you to add routing rules - i.e.

'''
<RoutingRule>
    <Condition>
        <KeyPrefixEquals>old/old.html</KeyPrefixEquals>
    </Condition>
    <Redirect>
        <HostName>cdnjs.cloudflare.com</HostName>
        <Protocol>https</Protocol>
        <HttpRedirectCode>301</HttpRedirectCode>
        <ReplaceKeyWith>ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js</ReplaceKeyWith>
    </Redirect>
</RoutingRule>
'''

**Comment by Dolondro** [comment]
Heya! Thanks for the ideas! Cache-Control is something we already have enabled on the bucket, certainly perpetual caching is not something that would hurt us at all in this regard (I can't imagine people wanting the code they're using changing beneath them anyway) but it doesn't seem to have made much of a dint.

Regarding static hosting, one of our team had a conversation with one of the guys at AWS regarding whether we could enable static website hosting and (my understanding is) that he said it pointed to a different endpoint, so as we're (stupidly in retrospect) pointing directly at the S3 URL we can't do anything about it =[
